
1. 先にカテゴリを作っておく


###
# CREATE スレッドの投稿
POST http://localhost:3333/api/v1/threadcreate HTTP/1.1
content-type: application/json

{
   "cid":{"id":1},
    "title": "新規投稿する",
    "name":"name",
    "text": "あああ",
    "editkey":"1122",

}

###
# CREATE メッセージの投稿
POST http://localhost:3333/api/v1/messagecreate HTTP/1.1
content-type: application/json

{
    "tid":{"id":1},
    "text":"削除するよ ",
    "name":"あああ",
    "editkey":"1111"
}


###
# READ threadごとに読み込み
GET  http://localhost:3333/api/v1/threadread?id=1 HTTP/1.1
content-type: application/json


###
# READ thread すべて読み込み
GET  http://localhost:3333/api/v1/threadallread HTTP/1.1
content-type: application/json


###
# READ category カテゴリーだけを読み込み
GET  http://localhost:3333/api/v1/categoriesread HTTP/1.1
content-type: application/json


###
# READ category カテゴリーごとに読み込み
GET  http://localhost:3333/api/v1/categoryread?id=1 HTTP/1.1
content-type: application/json






###
# READ Message メッセージごとに読み込み
GET  http://localhost:3333/api/v1/messageread HTTP/1.1
content-type: application/json

{

    "id": 1
}

###
# UPDATE Message メッセージを更新
POST   http://localhost:3333/api/v1/messageupdate HTTP/1.1
content-type: application/json

{

   "id":1,
    "name":"・ω・",
    "text": "・x・",
    "editkey":"1111",
     "tid":{"id":1}


}


###
# DELETE Message メッセージ削除
POST  http://localhost:3333/api/v1/messagedelete HTTP/1.1
content-type: application/json

{

    "id":6,
    "editkey":"1111"
}


###
# DELETE Thread スレッド削除
GET  http://localhost:3333/api/v1/delete HTTP/1.1
content-type: application/json

{
    "id": 1
}

