
1. 先にカテゴリを作っておく


#-------------------------
# Message
#-------------------------
###
# CREATE スレッド新規投稿
POST http://localhost:3333/api/v1/message HTTP/1.1
content-type: application/json

{

    "title": "新規投稿する",
    "name":"name",
    "text": "あああ",
    "editkey":"1122"
}

###
# CREATE メッセージ新規投稿
POST http://localhost:3333/api/v1/createmessage HTTP/1.1
content-type: application/json

{
    "tid":{"id":1},
    "text":"削除するよ ",
    "name":"あああ",
    "editkey":"1111"
}


###
# READ threadごとに読み込み
GET  http://localhost:3333/api/v1/thread?id=1 HTTP/1.1
content-type: application/json


###
# READ thread すべて読み込み
GET  http://localhost:3333/api/v1/threadall HTTP/1.1
content-type: application/json


###
# READ category カテゴリーだけを読み込み
GET  http://localhost:3333/api/v1/categories HTTP/1.1
content-type: application/json


###
# READ category カテゴリーごとに読み込み
GET  http://localhost:3333/api/v1/category?id=3 HTTP/1.1
content-type: application/json


###
# READ Message メッセージごとに読み込み
GET  http://localhost:3333/api/v1/findmessage HTTP/1.1
content-type: application/json

{

    "id": 3
}

###
# UPDATE Message メッセージを更新
POST   http://localhost:3333/api/v1/update HTTP/1.1
content-type: application/json

{

   "id":4,
    "name":"・ω・",
    "text": "・x・",
    "editkey":"1111",
     "tid":{"id":1}


}

###
# DELETE Thread スレッド削除
GET  http://localhost:3333/api/v1/delete HTTP/1.1
content-type: application/json

{
    "id": 1
}


###
# DELETE Message メッセージ削除
GET  http://localhost:3333/api/v1/deleteres HTTP/1.1
content-type: application/json

{

    "id":10,
    "editkey":"1111"
}
