@endpoint=http://localhost:3333/api/v1

###
# READ thread すべて読み込み
GET  {{endpoint}}/allread HTTP/1.1
content-type: application/json


###
# READ category カテゴリーだけを読み込み
GET {{endpoint}}/categoriesread HTTP/1.1
content-type: application/json


###
# READ category カテゴリーごとに読み込み
GET  {{endpoint}}/categoryread?id=2 HTTP/1.1
content-type: application/json

