@endpoint=http://localhost:3333/api/v1


###
# CREATE メッセージの投稿
POST {{endpoint}}/messagecreate HTTP/1.1
content-type: application/json

{
    "tid":{"id":10},
    "text":"あああああ ",
    "name":"いいい",
    "editkey":"1111"
}

###
# READ Message メッセージごとに読み込み
GET  {{endpoint}}/messageread HTTP/1.1
content-type: application/json

{

    "id": 1
}

###
# UPDATE Message メッセージを更新
POST   {{endpoint}}/messageupdate HTTP/1.1
content-type: application/json

{

   "id":2,
    "name":"おなまえ",
    "text": "・x・",
    "editkey":"1122",
     "tid":{"id":2}


}


###
# DELETE Message メッセージ削除
POST  {{endpoint}}/messagedelete HTTP/1.1
content-type: application/json

{

    "id":6,
    "editkey":"1111"
}



