
1. 先にカテゴリを作っておく


#-------------------------
# Message
#-------------------------
###
# CREATE スレッド新規投稿
POST http://localhost:3333/api/v1/message HTTP/1.1
content-type: application/json

{

    "title": "てすと３",
    "cid":{"id":3},
    "name":"テストさん",
    "text": "テスト３",
    "editkey":"1122"
}

###
# CREATE メッセージ新規投稿
POST http://localhost:3333/api/v1/createmessage HTTP/1.1
content-type: application/json

{
    "tid":{"id":5},
    "text":"３",
    "name":"3",
    "editkey":"1111"
}


###
# READ thread 個別読み込み
GET  http://localhost:3333/api/v1/thread HTTP/1.1
content-type: application/json

{

    "id": 1
}

###
# READ thread すべて読み込み
GET  http://localhost:3333/api/v1/threadall HTTP/1.1
content-type: application/json
###
# READ category カテゴリーごとに読み込み
GET  http://localhost:3333/api/v1/category HTTP/1.1
content-type: application/json


###
# READ Message メッセージごとに読み込み
GET  http://localhost:3333/api/v1/findmessage HTTP/1.1
content-type: application/json

{

    "id": 3
}

###
# UPDATE Message メッセージを更新
POST   http://localhost:3333/api/v1/update HTTP/1.1
content-type: application/json

{

   "id":12,
    "name":"こうき隊士",
    "text": "煉獄さん大好き！炎の呼吸！！！",
    "editkey":"1122"
}

###
# DELETE Thread スレッド削除
GET  http://localhost:3333/api/v1/delete HTTP/1.1
content-type: application/json

{
    "id": 1
}


###
# DELETE Message メッセージ削除
GET  http://localhost:3333/api/v1/deleteres HTTP/1.1
content-type: application/json

{

    "id": 64,
    "editkey":"111"
}
